---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "studio.fullname" . }}-mark-incomplete-job-config
  labels:
    tier: job
    app: {{ template "studio.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  DJANGO_LOG_FILE: /var/log/django.log
  DATA_DB_HOST: {{ template "cloudsql-proxy.fullname" . }}
  DATA_DB_PORT: "5432"
  MPLBACKEND: PS
  RUN_MODE: k8s
  RELEASE_COMMIT_SHA: {{ .Values.studioApp.releaseCommit | default "" }}
  BRANCH_ENVIRONMENT: {{ .Release.Name }}
  AWS_BUCKET_NAME: {{ .Values.studioApp.gcs.bucketName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "studio.fullname" . }}-mark-incomplete-job-secrets
  labels:
    app: {{ template "studio.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  DATA_DB_USER: {{ index .Values "cloudsql-proxy" "credentials" "username" | b64enc }}
  DATA_DB_PASS: {{ index .Values "cloudsql-proxy" "credentials" "password" | b64enc }}
  DATA_DB_NAME: {{ index .Values "cloudsql-proxy" "credentials" "dbname" | b64enc }}
  SENTRY_DSN_KEY: {{ .Values.sentry.dsnKey | b64enc }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mark-incomplete-cronjob
  labels:
    tier: job
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  schedule: "00 12 10 */36 *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: app
            image: {{ .Values.studioApp.imageName }}
            command:
            - python
            - contentcuration/manage.py
            - mark_incomplete
            env:
            - name: DJANGO_SETTINGS_MODULE
              value: contentcuration.production_settings
            envFrom:
            - configMapRef:
                name: {{ template "studio.fullname" . }}-mark-incomplete-job-config
            - secretRef:
                name: {{ template "studio.fullname" . }}-mark-incomplete-job-secrets
            resources:
              requests:
                cpu: 0.5
                memory: 1Gi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: full-gcp-access-scope
                    operator: In
                    values:
                    - "true"
